web:
    image: webdevops/php-apache:8.4@sha256:aba9ea5a3bd85b133f0ca63c7ff1a38ca01ef464929944b69818217d96935036
    ports:
    - "80:80"
    links:
    - db
    volumes:
    - $PWD:/app
    environment:
        DB_DATABASE: "${MYSQL_DATABASE}"
        DB_USER: "${MYSQL_USER}"
        DB_PASSWD: "${MYSQL_PASSWORD}"
        DB_HOST: "${MYSQL_HOST}"

db:
    image: mysql@sha256:6c4bb839cbeb064c8bdd671a0930ab77198552d08ca228954d5f1ffcf5e2a245
    ports:
    - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
